"""BSL -> Lean 4 semantics.

Emits the denotational semantics of a mass-action model:

  * an inductive `Species`,
  * a `Params` structure with an interval-bound `Params.Valid` predicate
    (the confidence-graded assumptions from the BSL source),
  * the mass-action vector field `dXdt`, and
  * one theorem per declared invariant asserting d/dt(invariant) = 0.

The conservation theorems are real and, for genuine conservation laws, close by
`simp only [dXdt]; ring`. This module emits the Lean text; running Lean to
*discharge* the proofs (the kernel check) is the next milestone. The output
requires a Lean 4 toolchain with Mathlib.
"""

from __future__ import annotations

from ..nodes import Model, Reaction


def _fmt(v: float) -> str:
    return str(int(v)) if v == int(v) else repr(v)


def _flux(r: Reaction) -> str:
    parts = [f"p.{r.rate_param}"]
    for ref in r.reactants:
        if ref.coeff == 1.0:
            parts.append(f"x {ref.species}")
        else:
            parts.append(f"x {ref.species} ^ {_fmt(ref.coeff)}")
    return " * ".join(parts)


def _net(r: Reaction, species: str) -> float:
    produced = sum(ref.coeff for ref in r.products if ref.species == species)
    consumed = sum(ref.coeff for ref in r.reactants if ref.species == species)
    return produced - consumed


def _dxdt_rhs(model: Model, species: str) -> str:
    terms: list[tuple[str, str]] = []  # (sign, magnitude-expr)
    for r in model.reactions:
        c = _net(r, species)
        if c == 0:
            continue
        flux = _flux(r)
        mag = f"({flux})" if abs(c) == 1.0 else f"{_fmt(abs(c))} * ({flux})"
        terms.append(("+" if c > 0 else "-", mag))
    if not terms:
        return "0"
    sign0, mag0 = terms[0]
    out = mag0 if sign0 == "+" else f"-{mag0}"
    for sign, mag in terms[1:]:
        out += f" {sign} {mag}"
    return out


def emit_lean(model: Model) -> str:
    L: list[str] = []
    sp = [s.name for s in model.species]

    L.append(f"/- Auto-generated by GSK-LeanBio from {model.source.name}. -/")
    L.append(f"/- Model: {model.name}. Do not edit by hand. -/")
    L.append("import Mathlib")
    L.append("")
    L.append(f"namespace BSL.{model.name}")
    L.append("")
    L.append("/-- Species of the model. -/")
    L.append(f"inductive Species | {' | '.join(sp)}")
    L.append("  deriving DecidableEq, Repr")
    L.append("")
    L.append("open Species")
    L.append("")
    L.append("/-- Rate constants. -/")
    L.append("structure Params where")
    for p in model.params:
        L.append(f"  {p.name} : ℝ")
    L.append("")
    L.append("/-- Interval assumptions over the parameters (confidence-graded "
             "in BSL). -/")
    L.append("structure Params.Valid (p : Params) : Prop where")
    for p in model.params:
        L.append(f"  {p.name}_lo : {_fmt(p.lo)} ≤ p.{p.name}    -- {p.grade}")
        L.append(f"  {p.name}_hi : p.{p.name} ≤ {_fmt(p.hi)}")
    L.append("")
    L.append("/-- Mass-action vector field  dX/dt. -/")
    L.append("def dXdt (p : Params) (x : Species → ℝ) : Species → ℝ")
    for s in sp:
        L.append(f"  | {s} => {_dxdt_rhs(model, s)}")
    L.append("")
    for inv in model.invariants:
        lhs = " + ".join(
            (f"dXdt p x {ref.species}" if ref.coeff == 1.0
             else f"{_fmt(ref.coeff)} * dXdt p x {ref.species}")
            for ref in inv.terms
        )
        expr = " + ".join(
            (ref.species if ref.coeff == 1.0 else f"{_fmt(ref.coeff)}*{ref.species}")
            for ref in inv.terms
        )
        L.append(f"/-- Conservation: BSL invariant `{inv.name}` states "
                 f"{expr} = {_fmt(inv.rhs)};")
        L.append(f"    equivalently d/dt({expr}) = 0. -/")
        L.append(f"theorem {inv.name} (p : Params) (x : Species → ℝ) :")
        L.append(f"    {lhs} = 0 := by")
        L.append("  simp only [dXdt]")
        L.append("  ring")
        L.append("")
    L.append(f"end BSL.{model.name}")
    L.append("")
    return "\n".join(L)
